### ISSUE TITLE
Code beauty - sorted imports

### ISSUE THREAD

**Issue by A-Telfer** [Helenel430/Quality-Classifier-Model#2]
This issue is code beauty, it's very low priority but nice when you're publishing things and want to impress people with the code quality

All your imports should be at the top, ideally they should be sorted so people can easily see what you're importing and from where
https://github.com/Helenel430/Quality-Classifier-Model/blob/9413e3597b09207122062af297d6f1ca5f3a7255/main#L1-L10

The order should be 
- Python builtin packages, installed packages, and project packages (ones you wrote are often separated). 
- Within each group, you general do the `import`s followed by the `from ... import`s
- For more details: https://peps.python.org/pep-0008/#imports

Rather than doing it ourselves, most people use a package called isort, eg `isort main.py`

**Comment by Helenel430** [comment]
Done thank you!!
