### ISSUE TITLE
Refactor classes

### ISSUE THREAD

**Issue by A-Telfer** [Helenel430/Quality-Classifier-Model#3]
Try moving your classes to new files and import them
 e.g. HomeworkDataset(Dataset) -> homework_dataset.py. The import would look like `from homework_dataset import HomeworkDataset `

I would also rename Homework Dataset to be something more descriptive

---
Modularizing parts of code is good practice and will make it look cleaner, it's also a good thing to practice for larger projects. Ideally each file should be relatively small and easy to read

**Comment by Helenel430** [comment]
Got it thank you!!
